/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.Address;
import javax.swing.JOptionPane;

/**
 *
 * @author fabio
 */
public class CreateLocalAddressJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateLocalAddressJPanel
     */
    Address localAddress;
    
    public CreateLocalAddressJPanel(Address a) {
        initComponents();
        localAddress = a;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblZipCode = new javax.swing.JLabel();
        fieldUnitNum = new javax.swing.JTextField();
        fieldCity = new javax.swing.JTextField();
        fieldState = new javax.swing.JTextField();
        fieldZipCode = new javax.swing.JTextField();
        lblCreateLocalAddress = new javax.swing.JLabel();
        lblStreet = new javax.swing.JLabel();
        lblUnitNumber = new javax.swing.JLabel();
        lblCity = new javax.swing.JLabel();
        lblState = new javax.swing.JLabel();
        fieldStreet = new javax.swing.JTextField();
        lblSave = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 204));

        lblZipCode.setText("Zip Code");

        fieldUnitNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldUnitNumActionPerformed(evt);
            }
        });

        lblCreateLocalAddress.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblCreateLocalAddress.setText("Create Local Address");

        lblStreet.setText("Street");

        lblUnitNumber.setText("Unit Number");

        lblCity.setText("City");

        lblState.setText("State");

        fieldStreet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldStreetActionPerformed(evt);
            }
        });

        lblSave.setText("Save");
        lblSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUnitNumber)
                    .addComponent(lblStreet)
                    .addComponent(lblCity)
                    .addComponent(lblState)
                    .addComponent(lblZipCode))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 151, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(fieldZipCode, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fieldState, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fieldCity, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fieldStreet, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fieldUnitNum, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(lblCreateLocalAddress))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(lblSave)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(lblCreateLocalAddress)
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStreet)
                    .addComponent(fieldStreet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUnitNumber)
                    .addComponent(fieldUnitNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCity)
                    .addComponent(fieldCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblState)
                    .addComponent(fieldState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblZipCode)
                    .addComponent(fieldZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(lblSave)
                .addContainerGap(143, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void fieldUnitNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldUnitNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldUnitNumActionPerformed

    private void lblSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblSaveActionPerformed
        // TODO add your handling code here:
        String street = fieldStreet.getText().trim();
        String unit   = fieldUnitNum.getText().trim();
        String city   = fieldCity.getText().trim();
        String state  = fieldState.getText().trim();
        String zip    = fieldZipCode.getText().trim();

        // 1) Null/empty checks
        if (street.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Street Name is required.");
        return;
        } else if (unit.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Unit Number is required.");
        return;
        } else if (city.isEmpty()) {
        JOptionPane.showMessageDialog(this, "City is required.");
        return;
        } else if (state.isEmpty()) {
        JOptionPane.showMessageDialog(this, "State is required.");
        return;
        } else if (zip.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Zip Code is required.");
        return;
        }

        // 2) Data type validation 
        
        try {
        Integer.parseInt(zip);
        } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Zip Code must be numeric (e.g., 14620).");
        return;
        }

        // 3) Save into Address object
        localAddress.setStreetName(street);
        localAddress.setUnitNum(unit);
        localAddress.setCity(city);
        localAddress.setState(state);
        localAddress.setZipCode(zip);

        JOptionPane.showMessageDialog(this, "Local Address saved successfully.");

        // 4) Clear fields after success
        fieldStreet.setText("");
        fieldUnitNum.setText("");
        fieldCity.setText("");
        fieldState.setText("");
        fieldZipCode.setText("");
    }//GEN-LAST:event_lblSaveActionPerformed

    private void fieldStreetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldStreetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldStreetActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fieldCity;
    private javax.swing.JTextField fieldState;
    private javax.swing.JTextField fieldStreet;
    private javax.swing.JTextField fieldUnitNum;
    private javax.swing.JTextField fieldZipCode;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblCreateLocalAddress;
    private javax.swing.JButton lblSave;
    private javax.swing.JLabel lblState;
    private javax.swing.JLabel lblStreet;
    private javax.swing.JLabel lblUnitNumber;
    private javax.swing.JLabel lblZipCode;
    // End of variables declaration//GEN-END:variables
}
