/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.Bank;
import javax.swing.JOptionPane;

/**
 *
 * @author fabio
 */
public class CreateBankAccountJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateBankAccountJPanel
     */
    Bank bank;
    
    public CreateBankAccountJPanel(Bank b) {
        initComponents();
        bank = b;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCreateBankAccount = new javax.swing.JLabel();
        lblBankName = new javax.swing.JLabel();
        lblAccountHolderName = new javax.swing.JLabel();
        lblAccountNumber = new javax.swing.JLabel();
        lblRoutingNumber = new javax.swing.JLabel();
        lblBalance = new javax.swing.JLabel();
        lblAccountType = new javax.swing.JLabel();
        fieldBankName = new javax.swing.JTextField();
        fieldAccountHolderName = new javax.swing.JTextField();
        fieldAccountNumber = new javax.swing.JTextField();
        fieldRoutingNumber = new javax.swing.JTextField();
        fieldBalance = new javax.swing.JTextField();
        fieldAccountType = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 204));

        lblCreateBankAccount.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblCreateBankAccount.setText("Create Bank Account");

        lblBankName.setText("Bank Name");

        lblAccountHolderName.setText("Account Holder Name");

        lblAccountNumber.setText("Account Number");

        lblBalance.setText("Balance");

        lblAccountType.setText("Account Type");

        fieldAccountHolderName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldAccountHolderNameActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAccountHolderName)
                    .addComponent(lblBankName)
                    .addComponent(lblAccountNumber)
                    .addComponent(lblRoutingNumber)
                    .addComponent(lblBalance)
                    .addComponent(lblAccountType))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(fieldAccountType)
                    .addComponent(fieldBalance, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fieldRoutingNumber, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fieldAccountNumber, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fieldBankName, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fieldAccountHolderName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(lblCreateBankAccount))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(btnSave)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(lblCreateBankAccount)
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBankName)
                    .addComponent(fieldBankName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAccountHolderName)
                    .addComponent(fieldAccountHolderName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAccountNumber)
                    .addComponent(fieldAccountNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRoutingNumber)
                    .addComponent(fieldRoutingNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBalance)
                    .addComponent(fieldBalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAccountType)
                    .addComponent(fieldAccountType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSave)
                .addContainerGap(131, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void fieldAccountHolderNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldAccountHolderNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldAccountHolderNameActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        String bankName = fieldBankName.getText().trim();
        String holder   = fieldAccountHolderName.getText().trim();
        String accNum   = fieldAccountNumber.getText().trim();
        String routing  = fieldRoutingNumber.getText().trim();
        String balText  = fieldBalance.getText().trim();
        String type     = fieldAccountType.getText().trim();

        // 1) Null / empty validation
        if (bankName.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Bank Name is required.");
        return;
        } else if (holder.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Account Holder Name is required.");
        return;
        } else if (accNum.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Account Number is required.");
        return;
        } else if (routing.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Routing Number is required.");
        return;
        } else if (balText.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Balance is required.");
        return;
        } else if (type.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Account Type is required.");
        return;
        }

        // 2) Numeric validation
        if (!accNum.matches("\\d+")) {
        JOptionPane.showMessageDialog(this, "Account Number must be numeric.");
        return;
        }

        if (!routing.matches("\\d+")) {
        JOptionPane.showMessageDialog(this, "Routing Number must be numeric.");
        return;
        }

        double balance;
        try {
        balance = Double.parseDouble(balText);
        if (balance < 0) {
            JOptionPane.showMessageDialog(this, "Balance cannot be negative.");
            return;
        }
        } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Balance must be a number (e.g., 2500.75).");
        return;
        }

        // 3) Save into Bank object
        bank.setBankName(bankName);
        bank.setAccountHolderName(holder);
        bank.setAccountNumber(accNum);
        bank.setRoutingNumber(routing);
        bank.setBalance(balance);
        bank.setAccountType(type);

        JOptionPane.showMessageDialog(this, "Bank Account saved successfully.");

        // 4) Clear fields after save
        fieldBankName.setText("");
        fieldAccountHolderName.setText("");
        fieldAccountNumber.setText("");
        fieldRoutingNumber.setText("");
        fieldBalance.setText("");
        fieldAccountType.setText("");
        
        
        
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JTextField fieldAccountHolderName;
    private javax.swing.JTextField fieldAccountNumber;
    private javax.swing.JTextField fieldAccountType;
    private javax.swing.JTextField fieldBalance;
    private javax.swing.JTextField fieldBankName;
    private javax.swing.JTextField fieldRoutingNumber;
    private javax.swing.JLabel lblAccountHolderName;
    private javax.swing.JLabel lblAccountNumber;
    private javax.swing.JLabel lblAccountType;
    private javax.swing.JLabel lblBalance;
    private javax.swing.JLabel lblBankName;
    private javax.swing.JLabel lblCreateBankAccount;
    private javax.swing.JLabel lblRoutingNumber;
    // End of variables declaration//GEN-END:variables


