/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.Person;
import Model.Address;
import javax.swing.JOptionPane;

/**
 *
 * @author fabio
 */
public class CreatePersonJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreatePersonJPanel
     */
    Person person;
    public CreatePersonJPanel(Person p) {
        initComponents();
        person = p;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        checkMarried = new javax.swing.JCheckBox();
        fieldLastName = new javax.swing.JTextField();
        fieldAge = new javax.swing.JTextField();
        lblCreatePerson = new javax.swing.JLabel();
        lblFirstName = new javax.swing.JLabel();
        lblLastName = new javax.swing.JLabel();
        lblAge = new javax.swing.JLabel();
        lblMarried = new javax.swing.JLabel();
        fieldFirstName = new javax.swing.JTextField();
        lblZipCode1 = new javax.swing.JLabel();
        fieldUnitNumHomeAddress = new javax.swing.JTextField();
        fieldCityHomeAddress = new javax.swing.JTextField();
        fieldStateHomeAddress = new javax.swing.JTextField();
        fieldZipCodeHomeAddress = new javax.swing.JTextField();
        lblStreetNameHomeAddress = new javax.swing.JLabel();
        lblUnitNumHomeAddress = new javax.swing.JLabel();
        lblCity = new javax.swing.JLabel();
        lblState = new javax.swing.JLabel();
        fieldStreetNameHomeAddress = new javax.swing.JTextField();
        lblZipCode2 = new javax.swing.JLabel();
        fieldUnitNumLocalAddress = new javax.swing.JTextField();
        fieldCityLocalAddress = new javax.swing.JTextField();
        fieldStateLocalAddress = new javax.swing.JTextField();
        fieldZipCodeLocalAddress = new javax.swing.JTextField();
        lblStreetNameLocalAddress = new javax.swing.JLabel();
        lblUnitNumLocalAddress = new javax.swing.JLabel();
        lblCityLocalAddress = new javax.swing.JLabel();
        lblStateLocalAddress = new javax.swing.JLabel();
        fieldStreetNameLocalAddress = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 204));

        checkMarried.setText("Yes");

        lblCreatePerson.setText("Create Person");

        lblFirstName.setText("First Name");

        lblLastName.setText("Last Name");

        lblAge.setText("Age");

        lblMarried.setText("Married");

        lblZipCode1.setText("Zip Code");

        lblStreetNameHomeAddress.setText("Street Name");

        lblUnitNumHomeAddress.setText("Unit Number");

        lblCity.setText("City");

        lblState.setText("State");

        lblZipCode2.setText("Zip Code");

        lblStreetNameLocalAddress.setText("Street Name");

        lblUnitNumLocalAddress.setText("Unit Number");

        lblCityLocalAddress.setText("City");

        lblStateLocalAddress.setText("State");

        jLabel1.setText("Home Address");

        jLabel2.setText("Local Address");

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFirstName)
                            .addComponent(lblLastName)
                            .addComponent(lblAge)
                            .addComponent(lblMarried))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(checkMarried)
                            .addComponent(fieldLastName, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(fieldAge)
                            .addComponent(fieldFirstName, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE))
                        .addGap(38, 38, 38))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblStreetNameHomeAddress)
                                        .addGap(27, 27, 27)
                                        .addComponent(fieldStreetNameHomeAddress))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblZipCode1)
                                            .addComponent(lblUnitNumHomeAddress)
                                            .addComponent(lblCity)
                                            .addComponent(lblState))
                                        .addGap(23, 23, 23)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(fieldZipCodeHomeAddress)
                                            .addComponent(fieldStateHomeAddress)
                                            .addComponent(fieldCityHomeAddress)
                                            .addComponent(fieldUnitNumHomeAddress))))
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(125, 125, 125)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblZipCode2)
                                    .addComponent(lblUnitNumLocalAddress)
                                    .addComponent(lblCityLocalAddress)
                                    .addComponent(lblStateLocalAddress)
                                    .addComponent(lblStreetNameLocalAddress))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(fieldStreetNameLocalAddress, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                                    .addComponent(fieldZipCodeLocalAddress)
                                    .addComponent(fieldStateLocalAddress)
                                    .addComponent(fieldUnitNumLocalAddress)
                                    .addComponent(fieldCityLocalAddress))
                                .addContainerGap())
                            .addGroup(layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(jLabel2)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(lblCreatePerson))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(btnSave)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(lblCreatePerson)
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblFirstName)
                    .addComponent(fieldFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLastName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAge))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkMarried)
                    .addComponent(lblMarried))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblStreetNameHomeAddress)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fieldUnitNumHomeAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblUnitNumHomeAddress)
                            .addComponent(lblUnitNumLocalAddress))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fieldCityHomeAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCity)
                            .addComponent(lblCityLocalAddress))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fieldStateHomeAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblState)
                            .addComponent(lblStateLocalAddress))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblZipCode1)
                            .addComponent(fieldZipCodeHomeAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblZipCode2)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fieldStreetNameHomeAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblStreetNameLocalAddress)
                            .addComponent(fieldStreetNameLocalAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldUnitNumLocalAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldCityLocalAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldStateLocalAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldZipCodeLocalAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addComponent(btnSave)
                .addGap(32, 32, 32))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        //Step 1: Collect text from the field
        String firstName = fieldFirstName.getText();
        String lastName = fieldLastName.getText();
        String ageText = fieldAge.getText();
        
        String homeStreet = fieldStreetNameHomeAddress.getText();
        String homeUnit   = fieldUnitNumHomeAddress.getText();
        String homeCity   = fieldCityHomeAddress.getText();
        String homeState  = fieldStateHomeAddress.getText();
        String homeZip    = fieldZipCodeHomeAddress.getText();
        
        String localStreet = fieldStreetNameLocalAddress.getText();
        String localUnit   = fieldUnitNumLocalAddress.getText();
        String localCity   = fieldCityLocalAddress.getText();
        String localState  = fieldStateLocalAddress.getText();
        String localZip    = fieldZipCodeLocalAddress.getText();
        
        // 2) Null / empty checks
        if (firstName.isEmpty()) {
        JOptionPane.showMessageDialog(this, "First Name is required.");
        return;
        } else if (lastName.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Last Name is required.");
        return;
        } else if (ageText.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Age is required.");
        return;
        } else if (homeStreet.isEmpty() || homeUnit.isEmpty() || homeCity.isEmpty() || homeState.isEmpty() || homeZip.isEmpty()) {
        JOptionPane.showMessageDialog(this, "All Home Address fields are required.");
        return;
        } else if (localStreet.isEmpty() || localUnit.isEmpty() || localCity.isEmpty() || localState.isEmpty() || localZip.isEmpty()) {
        JOptionPane.showMessageDialog(this, "All Local Address fields are required.");
        return;
        }

        // 3) Data type validation
        int age;
        try {
        age = Integer.parseInt(ageText.trim());
        } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Age must be a whole number (e.g., 25).");
        return;
        
        
}
        boolean married = checkMarried.isSelected();


        // 5) Save into Person object
        // (Assuming you have a Person variable in this panel like: private Person person;)
        
        person.setFirstName(firstName);
        person.setLastName(lastName);
        person.setAge(age);
        person.setMarried(married);
    
        // 6) Save home/local addresses
        Address homeAddress = person.getHomeAddress();   // since you init them in Person()
        homeAddress.setStreetName(homeStreet);
        homeAddress.setUnitNum(homeUnit);
        homeAddress.setCity(homeCity);
        homeAddress.setState(homeState);
        homeAddress.setZipCode(homeZip);

        Address localAddress = person.getLocalAddress();
        localAddress.setStreetName(localStreet);
        localAddress.setUnitNum(localUnit);
        localAddress.setCity(localCity);
        localAddress.setState(localState);
        localAddress.setZipCode(localZip);

        
        JOptionPane.showMessageDialog(this, "Person profile saved successfully.");
        
        // Clear all text fields
        fieldFirstName.setText("");
        fieldLastName.setText("");
        fieldAge.setText("");
        checkMarried.setSelected(false);

        // Home address
        fieldStreetNameHomeAddress.setText("");
        fieldUnitNumHomeAddress.setText("");
        fieldCityHomeAddress.setText("");
        fieldStateHomeAddress.setText("");
        fieldZipCodeHomeAddress.setText("");

        // Local address
        fieldStreetNameLocalAddress.setText("");
        fieldUnitNumLocalAddress.setText("");
        fieldCityLocalAddress.setText("");
        fieldStateLocalAddress.setText("");
        fieldZipCodeLocalAddress.setText("");
        
        
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JCheckBox checkMarried;
    private javax.swing.JTextField fieldAge;
    private javax.swing.JTextField fieldCityHomeAddress;
    private javax.swing.JTextField fieldCityLocalAddress;
    private javax.swing.JTextField fieldFirstName;
    private javax.swing.JTextField fieldLastName;
    private javax.swing.JTextField fieldStateHomeAddress;
    private javax.swing.JTextField fieldStateLocalAddress;
    private javax.swing.JTextField fieldStreetNameHomeAddress;
    private javax.swing.JTextField fieldStreetNameLocalAddress;
    private javax.swing.JTextField fieldUnitNumHomeAddress;
    private javax.swing.JTextField fieldUnitNumLocalAddress;
    private javax.swing.JTextField fieldZipCodeHomeAddress;
    private javax.swing.JTextField fieldZipCodeLocalAddress;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblCityLocalAddress;
    private javax.swing.JLabel lblCreatePerson;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblMarried;
    private javax.swing.JLabel lblState;
    private javax.swing.JLabel lblStateLocalAddress;
    private javax.swing.JLabel lblStreetNameHomeAddress;
    private javax.swing.JLabel lblStreetNameLocalAddress;
    private javax.swing.JLabel lblUnitNumHomeAddress;
    private javax.swing.JLabel lblUnitNumLocalAddress;
    private javax.swing.JLabel lblZipCode1;
    private javax.swing.JLabel lblZipCode2;
    // End of variables declaration//GEN-END:variables
}
