/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.Person;

/**
 *
 * @author fabio
 */
public class ViewPersonJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewPersonJPanel
     */
    Person person;
    public ViewPersonJPanel(Person p) {
        initComponents();
        person = p;
        display();
    }
    
    private void display() {
        fieldFirstName.setText(person.getFirstName());
        fieldLastName.setText(person.getLastName());
        fieldAge.setText(String.valueOf(person.getAge()));
        checkMarried.setSelected(person.isMarried());

    // Home Address
        if (person.getHomeAddress() != null) {
        fieldStreetNameHomeAddress.setText(person.getHomeAddress().getStreetName());
        fieldUnitNumHomeAddress.setText(person.getHomeAddress().getUnitNum());
        fieldCityHomeAddress.setText(person.getHomeAddress().getCity());
        fieldStateHomeAddress.setText(person.getHomeAddress().getState());
        fieldZipCodeHomeAddress.setText(person.getHomeAddress().getZipCode());
    }

    // Local Address
        if (person.getLocalAddress() != null) {
        fieldStreetNameLocalAddress.setText(person.getLocalAddress().getStreetName());
        fieldUnitNumLocalAddress.setText(person.getLocalAddress().getUnitNum());
        fieldCityLocalAddress.setText(person.getLocalAddress().getCity());
        fieldStateLocalAddress.setText(person.getLocalAddress().getState());
        fieldZipCodeLocalAddress.setText(person.getLocalAddress().getZipCode());
          }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblState = new javax.swing.JLabel();
        fieldStreetNameHomeAddress = new javax.swing.JTextField();
        lblZipCode2 = new javax.swing.JLabel();
        fieldUnitNumLocalAddress = new javax.swing.JTextField();
        fieldCityLocalAddress = new javax.swing.JTextField();
        fieldStateLocalAddress = new javax.swing.JTextField();
        fieldZipCodeLocalAddress = new javax.swing.JTextField();
        lblFirstName = new javax.swing.JLabel();
        lblStreetNameLocalAddress = new javax.swing.JLabel();
        lblLastName = new javax.swing.JLabel();
        lblUnitNumLocalAddress = new javax.swing.JLabel();
        lblCityLocalAddress = new javax.swing.JLabel();
        checkMarried = new javax.swing.JCheckBox();
        lblAge = new javax.swing.JLabel();
        lblStateLocalAddress = new javax.swing.JLabel();
        fieldLastName = new javax.swing.JTextField();
        lblMarried = new javax.swing.JLabel();
        fieldStreetNameLocalAddress = new javax.swing.JTextField();
        fieldAge = new javax.swing.JTextField();
        fieldFirstName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lblCreatePerson = new javax.swing.JLabel();
        lblZipCode1 = new javax.swing.JLabel();
        fieldUnitNumHomeAddress = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        fieldCityHomeAddress = new javax.swing.JTextField();
        fieldStateHomeAddress = new javax.swing.JTextField();
        fieldZipCodeHomeAddress = new javax.swing.JTextField();
        lblStreetNameHomeAddress = new javax.swing.JLabel();
        lblUnitNumHomeAddress = new javax.swing.JLabel();
        lblCity = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 204));

        lblState.setText("State");

        lblZipCode2.setText("Zip Code");

        lblFirstName.setText("First Name");

        lblStreetNameLocalAddress.setText("Street Name");

        lblLastName.setText("Last Name");

        lblUnitNumLocalAddress.setText("Unit Number");

        lblCityLocalAddress.setText("City");

        checkMarried.setText("Yes");

        lblAge.setText("Age");

        lblStateLocalAddress.setText("State");

        lblMarried.setText("Married");

        jLabel1.setText("Home Address");

        lblCreatePerson.setText("View Person");

        lblZipCode1.setText("Zip Code");

        jLabel2.setText("Local Address");

        lblStreetNameHomeAddress.setText("Street Name");

        lblUnitNumHomeAddress.setText("Unit Number");

        lblCity.setText("City");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFirstName)
                            .addComponent(lblLastName)
                            .addComponent(lblAge)
                            .addComponent(lblMarried))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(checkMarried)
                            .addComponent(fieldLastName, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(fieldAge)
                            .addComponent(fieldFirstName, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE))
                        .addGap(38, 38, 38))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblStreetNameHomeAddress)
                                        .addGap(27, 27, 27)
                                        .addComponent(fieldStreetNameHomeAddress))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblZipCode1)
                                            .addComponent(lblUnitNumHomeAddress)
                                            .addComponent(lblCity)
                                            .addComponent(lblState))
                                        .addGap(23, 23, 23)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(fieldZipCodeHomeAddress)
                                            .addComponent(fieldStateHomeAddress)
                                            .addComponent(fieldCityHomeAddress)
                                            .addComponent(fieldUnitNumHomeAddress))))
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(125, 125, 125)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblZipCode2)
                                    .addComponent(lblUnitNumLocalAddress)
                                    .addComponent(lblCityLocalAddress)
                                    .addComponent(lblStateLocalAddress)
                                    .addComponent(lblStreetNameLocalAddress))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(fieldStreetNameLocalAddress, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                                    .addComponent(fieldZipCodeLocalAddress)
                                    .addComponent(fieldStateLocalAddress)
                                    .addComponent(fieldUnitNumLocalAddress)
                                    .addComponent(fieldCityLocalAddress))
                                .addContainerGap())
                            .addGroup(layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(jLabel2)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
            .addGroup(layout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addComponent(lblCreatePerson)
                .addContainerGap(237, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(lblCreatePerson)
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblFirstName)
                    .addComponent(fieldFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLastName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAge))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkMarried)
                    .addComponent(lblMarried))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblStreetNameHomeAddress)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fieldUnitNumHomeAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblUnitNumHomeAddress)
                            .addComponent(lblUnitNumLocalAddress))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fieldCityHomeAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCity)
                            .addComponent(lblCityLocalAddress))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fieldStateHomeAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblState)
                            .addComponent(lblStateLocalAddress))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblZipCode1)
                            .addComponent(fieldZipCodeHomeAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblZipCode2)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fieldStreetNameHomeAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblStreetNameLocalAddress)
                            .addComponent(fieldStreetNameLocalAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldUnitNumLocalAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldCityLocalAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldStateLocalAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldZipCodeLocalAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(86, 86, 86))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox checkMarried;
    private javax.swing.JTextField fieldAge;
    private javax.swing.JTextField fieldCityHomeAddress;
    private javax.swing.JTextField fieldCityLocalAddress;
    private javax.swing.JTextField fieldFirstName;
    private javax.swing.JTextField fieldLastName;
    private javax.swing.JTextField fieldStateHomeAddress;
    private javax.swing.JTextField fieldStateLocalAddress;
    private javax.swing.JTextField fieldStreetNameHomeAddress;
    private javax.swing.JTextField fieldStreetNameLocalAddress;
    private javax.swing.JTextField fieldUnitNumHomeAddress;
    private javax.swing.JTextField fieldUnitNumLocalAddress;
    private javax.swing.JTextField fieldZipCodeHomeAddress;
    private javax.swing.JTextField fieldZipCodeLocalAddress;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblCityLocalAddress;
    private javax.swing.JLabel lblCreatePerson;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblMarried;
    private javax.swing.JLabel lblState;
    private javax.swing.JLabel lblStateLocalAddress;
    private javax.swing.JLabel lblStreetNameHomeAddress;
    private javax.swing.JLabel lblStreetNameLocalAddress;
    private javax.swing.JLabel lblUnitNumHomeAddress;
    private javax.swing.JLabel lblUnitNumLocalAddress;
    private javax.swing.JLabel lblZipCode1;
    private javax.swing.JLabel lblZipCode2;
    // End of variables declaration//GEN-END:variables

    
}
